version: '3.7'

services:
  web-server:
    image: web_server_image
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1
    networks:
      day_trade_net:
        aliases:
          - web_server
      
  audit-server:
    image: audit_server_image
    deploy:
      mode: replicated
      replicas: 1
    networks:
      day_trade_net:
        aliases:
          - audit_server
      
  add-service:
    image: add_service_image
    deploy:
      mode: replicated
      replicas: 1
    networks:
      day_trade_net:
        aliases:
          - add_service
      
  buy-service:
    image: buy_service_image
    deploy:
      mode: replicated
      replicas: 1
    networks:
      day_trade_net:
        aliases:
          - buy_service
      
  buy-trigger-service:
    image: buy_trigger_service_image
    deploy:
      mode: replicated
      replicas: 1
    networks:
      day_trade_net:
        aliases:
          - buy_trigger_service
      
  display-summary-service:
    image: display_summary_service_image
    deploy:
      mode: replicated
      replicas: 1
    networks:
      day_trade_net:
        aliases:
          - display_summary_service
      
  quote-service:
    image: quote_service_image
    deploy:
      mode: replicated
      replicas: 1
    networks:
      day_trade_net:
        aliases:
          - quote_service
      
  sell-service:
    image: sell_service_image
    deploy:
      mode: replicated
      replicas: 1
    networks:
      day_trade_net:
        aliases:
          - sell_service
      
  sell-trigger-service:
    image: sell_trigger_service_image
    deploy:
      mode: replicated
      replicas: 1
    networks:
      day_trade_net:
        aliases:
          - sell_trigger_service
    
  db:
    image: mysql/mysql-server:8.0.17
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      MYSQL_DATABASE: db
      # So you don't have to use root, but you can if you like
      MYSQL_USER: user
      # You can use whatever password you like
      MYSQL_PASSWORD: password
      # Password for root access
      MYSQL_ROOT_PASSWORD: password
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3306:3306"
      # Where our data will be persisted
    volumes:
      - ./DatabaseServer/data/init:/docker-entrypoint-initdb.d
    networks:
      day_trade_net:
        aliases:
          - databaseserver_db_1
              
      
  quote-server:
    image: quote_server_image
    deploy:
      mode: replicated
      replicas: 1
    networks:
      day_trade_net:
        aliases:
          - quoteserve.seng.uvic.ca

networks:
  day_trade_net:
    ipam:
      config:
        - subnet: 172.2.0.0/16